// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzttrybczojilxwbzyrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dHRyeWJjem9qaWx4d2J6eXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTk3NDQsImV4cCI6MjA1OTY3NTc0NH0.kQBV1MJ7aXJUL0z3viDhtbTPnThrQe6ixvhMCT7NzK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);